const work = [
  {
    imageUrl: "/yantemis.png",
    title: "Comic Subscription Platform",
    stack: "Next.js, Redux, Axios",
    anchorLink: "http://164.90.184.187:3000/",
    featured: true,
  },
  {
    imageUrl: "/apple clone.png",
    title: "Apple Vision Pro Clone",
    stack: "HTML, CSS, JavaScript, GSAP, Locomotive Scroll",
    anchorLink: "https://bhavikt5.github.io/apple-vision-pro-clone/",
    featured: true,
  },
  {
    imageUrl: "/zype.webp",
    title: "Fintech Company Website",
    stack: "WordPress, Elementor Pro, CPT, ACF, PHP",
    anchorLink: "https://www.getzype.com/",
    featured: true,
  },
  {
    imageUrl: "/aaylixir.webp",
    title: "Fashion E-commerce Store",
    stack: "WordPress, WooCommerce, Payment Integration, PHP",
    anchorLink: "https://theaaylixir.com/",
    featured: true,
  },
  {
    imageUrl: "/utsavaa.webp",
    title: "Wellness & Lifestyle Website",
    stack: "WordPress, Elementor, CPT, ACF",
    anchorLink: "https://utsavaa.com/",
    featured: true,
  },
  {
    imageUrl: "/acturemedia.webp",
    title: "Media Agency Website",
    stack: "WordPress, HTML, CSS, JavaScript",
    anchorLink: "https://acturemedia.com/",
    featured: true,
  },
  {
    imageUrl: "/cirocco.webp",
    title: "Fabric Brand Website",
    stack: "WordPress, HTML, CSS, JavaScript",
    anchorLink: "https://ciroccofabrics.com/",
  },
  {
    imageUrl: "/acetattooz.webp",
    title: "Tattoo Studio Website",
    stack: "WordPress, HTML, CSS, JavaScript",
    anchorLink: "https://acetattooz.com/",
  },
  {
    imageUrl: "/widgetorweb.png",
    title: "CRM Dashboard",
    stack: "HTML, CSS, JavaScript, jQuery, Bootstrap",
    anchorLink: "https://project5widgetor-dasboard.vercel.app/homepage.html",
  },
  {
    imageUrl: "/culinarycraft.webp",
    title: "Culinary E-commerce Store",
    stack: "WordPress, WooCommerce, WooLentor",
    anchorLink: "https://culinarycraft.in/",
  },
  {
    imageUrl: "/vistruti.webp",
    title: "E-commerce Website",
    stack: "WordPress, WooCommerce, HTML, CSS, JavaScript",
    anchorLink: "https://vistruti.in/",
  },
  {
    imageUrl: "/ecobirdfood.webp",
    title: "Bird Food E-commerce Store",
    stack: "WordPress, WooCommerce, HTML, CSS, JavaScript",
    anchorLink: "https://ecobirdfood.com/",
  },
  {
    imageUrl: "/mce.webp",
    title: "Machinery Company Website",
    stack: "WordPress, HTML, CSS, JavaScript",
    anchorLink: "https://mceteam.com/",
  },
  {
    imageUrl: "/respo.webp",
    title: "Fintech Website",
    stack: "WordPress, HTML, CSS, JavaScript",
    anchorLink: "https://respo.co.in/",
  },
  {
    imageUrl: "/widgetorWebsite.png",
    title: "Business Website",
    stack: "HTML, CSS, JavaScript, jQuery, Bootstrap",
    anchorLink: "https://project6widgetor.vercel.app/",
  },
  {
    imageUrl: "/qlik.png",
    title: "Business Website",
    stack: "HTML, CSS, JavaScript, jQuery, Bootstrap",
    anchorLink: "https://qlik-demo.vercel.app/",
  },
  {
    imageUrl: "/sushi.png",
    title: "Sushi Restaurant Website",
    stack: "HTML, CSS, JavaScript",
    anchorLink: "https://sushi-website-vert.vercel.app/",
  },
  {
    imageUrl: "/construction.png",
    title: "Construction Company Website",
    stack: "HTML, CSS, SCSS, JavaScript",
    anchorLink: "https://bhavikt5.github.io/Construction-Site/",
  },
  {
    imageUrl: "/realestate.png",
    title: "Real Estate Website",
    stack: "HTML, CSS, JavaScript",
    anchorLink: "https://realestate-two-rho.vercel.app/",
  },
];

export default work;
